### PR TITLE
README updates

### PR DESCRIPTION
**Pull request by jo285317**
`make debootstrap` and `make build-base` were out of order: the latter calls `make install-kernel-modules` which relies on the qemu disk being setup (through `mkfs.ext4 $(disk)` in `make debootstrap`)

also, there was a small typo regarding the constant.sh file

### CODE REVIEW

**Comment by hckuo** [comment]
`make debootstrap` has to be run first as it builds the vanilla kernel including LKMs that need to be in the root filesystem.

**Comment by hckuo** [comment]
Actually, $mnt and $disk are prerequisites of debootstrap so it works without explicitly specifying. But it's good to list them in the README.

**Comment by hckuo** [comment]
Correction: you were right about the order! Thank you for calling it out!

**Comment by tianyin** [comment]
Thank you @jo285317 !!

**Pull request merged**
