### PR TITLE
Revert "Minor fix"

### PR DESCRIPTION
**Pull request by hckuo**
Reverts hckuo/Cozart#21

### CODE REVIEW

**Comment by tianyin** [comment]
@hckuo are you sure it's `/Conzart`? `/` means root.

**Comment by ubdussamad** [comment]
@tianyin  It'll work both ways, hckuo 's path is absolute mine was relative.

**Comment by tianyin** [comment]
> It'll work both ways

I don't like absolute path. I think we should use relative path if possible.

**Comment by ubdussamad** [comment]
Although I personally don't like absolutes as well but here the `docker run ...` command (in the docs) always mounts the cozart folder in to the root of the container, so it's not a big issue to use absolute here. So finally, It's totally upon preference :)

**Pull request closed without merging**
